package entidades;
// Generated 14/07/2019 08:25:22 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String nombreUsuario;
     private String password;
     private String personal;

    public Usuario() {
    }

    public Usuario(int idUsuario, String nombreUsuario, String password, String personal) {
       this.idUsuario = idUsuario;
       this.nombreUsuario = nombreUsuario;
       this.password = password;
       this.personal = personal;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(String personal) {
        this.personal = personal;
    }




}


